version: "3.9"

services:
  facecheck_api:
    image: and3510/visionapp:develop
    container_name: facecheck_api
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./firebase_config.json:/app/firebase_config.json

  ssp_criminosos:
    image: pgvector/pgvector:pg17
    container_name: bd_criminosos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: and3872#
      POSTGRES_DB: ssp_criminosos
    ports:
      - "5432:5432"
    volumes:
      - pgdata_criminosos:/var/lib/postgresql/data

  ssp_usuarios:
    image: postgres:17
    container_name: bd_usuarios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: and3872#
      POSTGRES_DB: ssp_usuario
    ports:
      - "5433:5432"  # Evita conflito de porta com o primeiro PostgreSQL
    volumes:
      - pgdata_usuarios:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"  # Console web do MinIO
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

volumes:
  pgdata_usuarios:
  pgdata_criminosos:
  minio-data:


