sonar.projectKey=and3510_ApiVisionApp_Project_AZjTpjWuB_kcsVrfZep_
sonar.projectName=ApiVisionApp_Project
sonar.projectVersion=1.0

# Pastas com código-fonte
sonar.sources=functions,config,docker,.


# Ignorar arquivos/pastas irrelevantes
sonar.exclusions=**/__pycache__/**,**/.git/**,**/.env.example,**/*.png,**/*.jpg,**/*.drawio


# Linguagem (opcional, mas ajuda o SonarQube a reconhecer Python)
sonar.language=py

