sonar.projectKey=and3510_ApiVisionApp_Project_1443ea92-baa3-44e5-900c-ba4d27fdf893
sonar.sources=.,functions,config,docker
sonar.python.version=3.11

sonar.exclusions=**/__pycache__/**,**/.git/**,**/.env.example,**/*.png,**/*.jpg,**/*.drawio
