sonar.projectKey=and3510_ApiVisionApp_Project_1443ea92-baa3-44e5-900c-ba4d27fdf893
sonar.sources=.
sonar.python.version=3.11
#sonar.projectName=ApiVisionApp_Project
#sonar.projectVersion=1.0

# # Pastas com código-fonte
#sonar.sources=.,functions,config,docker



#Ignorar arquivos/pastas irrelevantes
#sonar.exclusions=**/__pycache__/**,**/.git/**,**/.env.example,**/*.png,**/*.jpg,**/*.drawio


# # Linguagem (opcional, mas ajuda o SonarQube a reconhecer Python)
sonar.language=py

