version: "3.9"

services:
  api_visionapp:
    image: and3510/visionapp:v2.6.3-develop
    container_name: api_visionapp
    labels:
      - "traefik.enable=true"

      # Router HTTPS
      - "traefik.http.routers.api_visionapp.rule=Host(`${FASTAPI_HOST}`)"
      - "traefik.http.routers.api_visionapp.entrypoints=websecure"
      - "traefik.http.routers.api_visionapp.tls.certresolver=${CERT_RESOLVER}"

      # Router HTTP → HTTPS
      - "traefik.http.routers.api_visionapp-http.rule=Host(`${FASTAPI_HOST}`)"
      - "traefik.http.routers.api_visionapp-http.entrypoints=web"
      - "traefik.http.routers.api_visionapp-http.middlewares=https-redirect"

      # Middleware de redirecionamento
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
      - ./firebase_config.json:/app/firebase_config.json
    networks:
      - web


  ssp_criminosos:
    image: pgvector/pgvector:pg17
    container_name: bd_criminosos
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${PG_CRIMINOSOS_PASSWORD}
      POSTGRES_DB: ssp_criminosos
    ports:
      - "5432:5432"
    volumes:
      - pgdata_criminosos:/var/lib/postgresql/data
    networks:
      - web


  ssp_usuarios:
    image: postgres:17
    container_name: bd_usuarios
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${PG_USUARIOS_PASSWORD}
      POSTGRES_DB: ssp_usuario
    ports:
      - "5433:5432"
    volumes:
      - pgdata_usuarios:/var/lib/postgresql/data
    networks:
      - web


  minio:
    image: minio/minio
    container_name: minio
    labels:
      - "traefik.enable=true"

      # --- MinIO API (9000) ---
      - "traefik.http.routers.minio.rule=Host(`${MINIO_HOST}`)"
      - "traefik.http.routers.minio.entrypoints=websecure"
      - "traefik.http.routers.minio.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.minio.service=minio-svc"
      - "traefik.http.services.minio-svc.loadbalancer.server.port=9000"

      - "traefik.http.routers.minio-http.rule=Host(`${MINIO_HOST}`)"
      - "traefik.http.routers.minio-http.entrypoints=web"
      - "traefik.http.routers.minio-http.middlewares=https-redirect"
      - "traefik.http.routers.minio-http.service=minio-svc"

      # --- MinIO Console (9001) ---
      - "traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_HOST}`)"
      - "traefik.http.routers.minio-console.entrypoints=websecure"
      - "traefik.http.routers.minio-console.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.minio-console.service=minio-console-svc"
      - "traefik.http.services.minio-console-svc.loadbalancer.server.port=9001"

      - "traefik.http.routers.minio-console-http.rule=Host(`${MINIO_CONSOLE_HOST}`)"
      - "traefik.http.routers.minio-console-http.entrypoints=web"
      - "traefik.http.routers.minio-console-http.middlewares=https-redirect"
      - "traefik.http.routers.minio-console-http.service=minio-console-svc"

      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"

    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio-data:/data
    networks:
      - web


volumes:
  pgdata_usuarios:
  pgdata_criminosos:
  minio-data:

networks:
  web:
    external: true
